### PR TITLE
60 fixed issue around gridgenerator

### LINKED ISSUE #58: Add initial values to charInfo

### LINKED ISSUE #60: Movement: Don't allow character to move onto squares where another character is standing

### LINKED ISSUE #61: Allow player to move one square ahead, and diagonally left and right in addition to two squares ahead

### LINKED ISSUE #62: Fix the UnassigendReferenceException, when there is no enemy on the selected tile, during "strike"

### LINKED ISSUE #70: Add a skip button to the `BattleMenu` so if a player doesn't want to move it will go to the next turn, this will also be useful if a player can't attack

### PR DESCRIPTION
**Pull request by unbekanntunity**
- changed name alias to ally
- deleted getObjectonTile.cs and created a new one
- added inital Values for charInfo 
- added skip button 

#58 , #60 , #61 , #62 , #70

### CODE REVIEW

File: Assets/Dev/B/Script/getObjectonTile.cs [hunk 1]
```diff
@@ -1,19 +1,35 @@
-﻿using System.Collections;
-using System.Collections.Generic;
-using UnityEngine;
+﻿using UnityEngine;
```
Comment (sirjust) [inline Assets/Dev/B/Script/getObjectonTile.cs]: This script is still named incorrectly. Try to delete it entirely in one commit, and make a new one with the right name in the next commit.

File: Assets/Dev/B/Script/EnemyAI.cs [hunk 2]
```diff
@@ -0,0 +1,168 @@
+﻿using System.Collections.Generic;
```
Comment (sirjust) [inline Assets/Dev/B/Script/EnemyAI.cs]: Enemy AI isn't part of this pull request. It needs to be removed

File: Assets/Dev/B/Script/CardSystem.cs [hunk 3]
```diff
@@ -80,10 +82,14 @@ public void PlayCard(int index)
 
     public void DrawCard()
     {
-        if (lastIndex != maxCardCount)
+        if (turnSystem.GetBattleStatus() == BattleStatus.PlayerCombat)
         {
-            InstantiateCard(lastIndex);
-            lastIndex++;
+            turnSystem.NextTurn();
```
Comment (sirjust) [inline Assets/Dev/B/Script/CardSystem.cs]: This looks problematic. Drawing a card shouldn't govern what happens in the turn system, and it looks like it's changing the turn before doing anything. When I draw a card, I'm getting a message that says 'select other tiles.' I think this is because the turn is going to enemy move

Comment (unbekanntunity) [reply Assets/Dev/B/Script/CardSystem.cs]: thats right, but I dont see the prolem here

File: Assets/Dev/B/Script/EnemyAI.cs (hunk 2 above)
Comment (unbekanntunity) [reply Assets/Dev/B/Script/EnemyAI.cs]: Done

File: Assets/Dev/B/Script/getObjectonTile.cs (hunk 1 above)
Comment (unbekanntunity) [reply Assets/Dev/B/Script/getObjectonTile.cs]: Done

**Review by sirjust — APPROVED** [review]
